### ISSUE TITLE
Security Exception - Permission Denied - No INTERNET Permission

### ISSUE THREAD

**Issue by aritraroy** [Karumi/FlowUpAndroidSDKIssueTracker#7]
I am getting this crash regularly because of FlowUp. Please look into this and let me know if there is a fix for this on the way. Otherwise, I have no other option that to remove it from my app. I don't want my app to crash because of this.

```
Fatal Exception: java.lang.SecurityException: Permission denied (missing INTERNET permission?)
       at java.net.InetAddress.lookupHostByName(InetAddress.java:479)
       at java.net.InetAddress.getAllByNameImpl(InetAddress.java:280)
       at java.net.InetAddress.getAllByName(InetAddress.java:243)
       at okhttp3.Dns$1.lookup(SourceFile:39)
       at okhttp3.internal.connection.RouteSelector.resetNextInetSocketAddress(SourceFile:170)
       at okhttp3.internal.connection.RouteSelector.nextProxy(SourceFile:136)
       at okhttp3.internal.connection.RouteSelector.next(SourceFile:81)
       at okhttp3.internal.connection.StreamAllocation.findConnection(SourceFile:181)
       at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(SourceFile:132)
       at okhttp3.internal.connection.StreamAllocation.newStream(SourceFile:101)
       at okhttp3.internal.connection.ConnectInterceptor.intercept(SourceFile:42)
       at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:92)
       at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:67)
       at okhttp3.internal.cache.CacheInterceptor.intercept(SourceFile:93)
       at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:92)
       at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:67)
       at okhttp3.internal.http.BridgeInterceptor.intercept(SourceFile:93)
       at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:92)
       at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(SourceFile:120)
       at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:92)
       at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:67)
       at io.flowup.b.d.intercept(Unknown Source)
       at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:92)
       at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:67)
       at io.flowup.b.e.intercept(Unknown Source)
       at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:92)
       at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:67)
       at okhttp3.RealCall.getResponseWithInterceptorChain(SourceFile:179)
       at okhttp3.RealCall.execute(SourceFile:63)
       at io.flowup.config.a.a.a(Unknown Source)
       at io.flowup.config.b.b(Unknown Source)
       at io.flowup.config.android.ConfigSyncService.a(Unknown Source)
       at io.flowup.config.android.ConfigSyncService.onRunTask(Unknown Source)
       at com.google.android.gms.gcm.GcmTaskService$zza.run(Unknown Source)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)
```

**Comment by aritraroy** [comment]
Any updates?

**Comment by pedrovgs** [comment]
Hi @aritraroy, sorry for the late response. The Android SDK requests this permission so this bug has to be related to your app and not the FlowUp Android SDK. Did you add this permission to your Android Manifest? It should be in the final manifest after the build, but we should check if there is something wrong with the manifest merger.

Can you specify the SDK version you are using? If you can constantly reproduce this issue it could be great if you can create an example project we can take a look at.

**Comment by aritraroy** [comment]
It is quite obvious that I have the INTERNET permission in my app. And this issue doesn't happen with all users, but only to a small portion of it.

But I can still see this crash almost regularly. I will be removing this soon considering how slow the dev support for this library is.

I am on version 0.2.7.

**Comment by pedrovgs** [comment]
I'm really sorry for the delay @aritraroy. Do you have any way to reproduce this issue? Could you share the link to the crash? We've just released a new version which could be interesting in this case, we've implemented a safety net so you won't see any crash related to the lib if you use this feature. It could be really helpful if we can find the steps to reproduce this bug using a sample project.

Thanks for your time.

**Comment by aritraroy** [comment]
Hi,

There is no way for me to reproduce this issue as it is happening for some random users and I don't have any access to their devices.

I have put the entire stack trace in the first comment in the thread. Please check that for more details.

I will also upgrade the library soon and test it out.

**Comment by pedrovgs** [comment]
As we can't reproduce the issue, we don't have information about if it's just reproducible on some android devices or OS versions and the latest version released catches these exceptions I'm closing this issue. Feel free to reopen it if you can reproduce it using the latest FlowUp Android SDK version released.

Thanks for your time and patience.
